<#
.SYNOPSIS
  Start Tilezilla in Docker for LAN / remote device testing (Windows 11).

.DESCRIPTION
  Brings up docker-compose.remote-test.yml:
    - nginx gateway on TILEZILLA_PORT (default 8080)
    - Python game server + PHP auth + MySQL

  Open the printed LAN URL from a phone or tablet on the same Wi‑Fi.

.EXAMPLE
  .\scripts\start-remote-test.ps1

.EXAMPLE
  .\scripts\start-remote-test.ps1 -Port 9080 -SeedUsers -OpenFirewall

.EXAMPLE
  .\scripts\start-remote-test.ps1 -LanIp 192.168.1.42
#>
[CmdletBinding()]
param(
  [int]$Port = 8080,
  [string]$LanIp = "",
  [switch]$SeedUsers,
  [switch]$OpenFirewall,
  [switch]$NoBuild
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$ComposeFile = Join-Path $RepoRoot "docker-compose.remote-test.yml"
$EnvFile = Join-Path $RepoRoot ".env.remote-test"

function Write-Step([string]$Message) {
  Write-Host ""
  Write-Host "==> $Message" -ForegroundColor Cyan
}

function Test-DockerReady {
  if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    throw "Docker is not installed. Install Docker Desktop for Windows 11 first."
  }
  docker info *> $null
  if ($LASTEXITCODE -ne 0) {
    throw "Docker Desktop is not running. Start Docker Desktop, then run this script again."
  }
}

function Get-LanIpAddress {
  param([string]$Preferred = "")

  if ($Preferred) {
    return $Preferred
  }

  $virtualAliasPattern = "vEthernet|WSL|Hyper-V|Default Switch|Docker|Loopback|Tailscale|ZeroTier|Hamachi|VirtualBox|VMware|Npcap|TAP|TUN|VPN"

  $candidates = @(
    Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
      Where-Object {
        $_.IPAddress -and
        $_.IPAddress -notlike "127.*" -and
        $_.IPAddress -notlike "169.254.*" -and
        $_.IPAddress -notlike "172.17.*" -and
        $_.IPAddress -notlike "172.18.*" -and
        $_.IPAddress -notlike "172.30.*" -and
        $_.PrefixOrigin -ne "WellKnown" -and
        $_.InterfaceAlias -notmatch $virtualAliasPattern
      } |
      Sort-Object -Property InterfaceMetric, PrefixLength
  )

  $wifi = $candidates | Where-Object { $_.InterfaceAlias -match "Wi-?Fi|WLAN|Wireless" } | Select-Object -First 1
  if ($wifi) { return $wifi.IPAddress }

  $eth = $candidates | Where-Object { $_.InterfaceAlias -match "^Ethernet(\s|$|\d)" } | Select-Object -First 1
  if ($eth) { return $eth.IPAddress }

  $any = $candidates | Select-Object -First 1
  if ($any) { return $any.IPAddress }

  return "127.0.0.1"
}

function Write-EnvFile {
  param(
    [string]$Path,
    [int]$Port,
    [string]$LanIp
  )

  $baseUrl = "http://${LanIp}:$Port"
  @"
# Generated by start-remote-test.ps1 — safe to edit and re-run the script.
TILEZILLA_PORT=$Port
APP_BASE_URL=$baseUrl
MYSQL_ROOT_PASSWORD=root_dev_change_me
MYSQL_DATABASE=tilegame
MYSQL_USER=tilegame
MYSQL_PASSWORD=tilegame_dev
APP_FROM_EMAIL=words@skifflakegames.com
APP_ADMIN_EMAIL=gar@hotmail.ca
"@ | Set-Content -Path $Path -Encoding UTF8
}

function Stop-HostGameServerOnPort {
  param([int]$Port)

  $listeners = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue
  if (-not $listeners) { return }

  foreach ($conn in $listeners) {
    $proc = Get-CimInstance Win32_Process -Filter "ProcessId=$($conn.OwningProcess)" -ErrorAction SilentlyContinue
    if (-not $proc) { continue }

    $cmd = [string]$proc.CommandLine
    if ($proc.Name -eq "python.exe" -and $cmd -match "scripts[\\/]+server\.py") {
      Write-Host "Stopping host Python dev server on port $Port (PID $($proc.ProcessId)) so Docker gateway can own the port." -ForegroundColor Yellow
      Stop-Process -Id $proc.ProcessId -Force -ErrorAction SilentlyContinue
    }
  }
}

function Wait-ComposeHealthy {
  param(
    [string]$ComposeFile,
    [string]$EnvFile,
    [int]$TimeoutSec = 180
  )

  $deadline = (Get-Date).AddSeconds($TimeoutSec)
  while ((Get-Date) -lt $deadline) {
    $mysql = docker compose -f $ComposeFile --env-file $EnvFile ps mysql --format json 2>$null | ConvertFrom-Json
    $gateway = docker compose -f $ComposeFile --env-file $EnvFile ps gateway --format json 2>$null | ConvertFrom-Json

    $mysqlOk = $mysql -and $mysql.State -eq "running" -and $mysql.Health -eq "healthy"
    $gatewayOk = $gateway -and $gateway.State -eq "running"

    if ($mysqlOk -and $gatewayOk) {
      return
    }

    Start-Sleep -Seconds 3
  }

  throw "Timed out waiting for mysql/gateway containers. Run: docker compose -f docker-compose.remote-test.yml logs"
}

function Ensure-FirewallRule {
  param([int]$Port)

  $ruleName = "Tilezilla Remote Test ($Port)"
  $existing = Get-NetFirewallRule -DisplayName $ruleName -ErrorAction SilentlyContinue
  if ($existing) {
    Write-Host "Firewall rule already exists: $ruleName" -ForegroundColor DarkGray
    return
  }

  if (-not (Get-Command New-NetFirewallRule -ErrorAction SilentlyContinue)) {
    Write-Host "Could not create firewall rule (New-NetFirewallRule unavailable). Allow TCP $Port manually if needed." -ForegroundColor Yellow
    return
  }

  New-NetFirewallRule `
    -DisplayName $ruleName `
    -Direction Inbound `
    -Action Allow `
    -Protocol TCP `
    -LocalPort $Port `
    -Profile Private, Domain | Out-Null

  Write-Host "Added Windows Firewall inbound rule for TCP $Port (Private/Domain)." -ForegroundColor Green
}

Push-Location $RepoRoot
try {
  Write-Step "Checking Docker"
  Test-DockerReady

  Write-Step "Ensuring port $Port is free for Docker gateway"
  Stop-HostGameServerOnPort -Port $Port

  Write-Step "Ensuring shared MySQL volume (preserves registered accounts)"
  $ensureVol = Join-Path $RepoRoot "scripts\ensure-shared-mysql-volume.ps1"
  if (Test-Path $ensureVol) {
    & $ensureVol
  }

  $LanIp = Get-LanIpAddress -Preferred $LanIp
  Write-Step "Writing $EnvFile"
  Write-EnvFile -Path $EnvFile -Port $Port -LanIp $LanIp

  if ($OpenFirewall) {
    Write-Step "Opening Windows Firewall for port $Port"
    Ensure-FirewallRule -Port $Port
  }

  $composeArgs = @(
    "compose",
    "-f", $ComposeFile,
    "--env-file", $EnvFile,
    "up",
    "-d"
  )
  if (-not $NoBuild) {
    $composeArgs += "--build"
  }

  Write-Step "Starting containers"
  & docker @composeArgs
  if ($LASTEXITCODE -ne 0) {
    throw "docker compose up failed (exit $LASTEXITCODE)"
  }

  Write-Step "Waiting for services"
  Wait-ComposeHealthy -ComposeFile $ComposeFile -EnvFile $EnvFile

  Write-Step "Seeding dev users (test / test for mobile auto-login)"
  $seedScript = Join-Path $RepoRoot "scripts\seed-remote-test-users.ps1"
  if (Test-Path $seedScript) {
    & $seedScript -ComposeFile $ComposeFile -EnvFile $EnvFile
  }

  if ($SeedUsers) {
    Write-Host "(-SeedUsers: gar and Arn also available for manual login)" -ForegroundColor DarkGray
  }

  $localUrl = "http://localhost:$Port"
  $lanUrl = "http://${LanIp}:$Port"
  $autoLoginUrl = "$localUrl/dev-auto-login.html"
  $lanAutoLoginUrl = "$lanUrl/dev-auto-login.html"

  Write-Step "Tilezilla remote test is running"
  Write-Host @"

  Skip login — open game directly (test / test):
    $autoLoginUrl

  From phone / tablet (same Wi-Fi):
    $lanAutoLoginUrl

  Manual login (if needed):
    $localUrl/login-screen.html
    test / test

  On this PC:
    $localUrl/tilezilla-v2.html

  Other dev logins:
    gar / gar
    Arn / arn

  Stop:
    .\scripts\stop-remote-test.ps1

  Logs:
    docker compose -f docker-compose.remote-test.yml --env-file .env.remote-test logs -f gateway web

"@ -ForegroundColor Green

  if (-not $OpenFirewall) {
    Write-Host "Tip: re-run with -OpenFirewall if other devices cannot connect." -ForegroundColor DarkYellow
  }
}
finally {
  Pop-Location
}
